#!/bin/bash
if [[ $XDG_SESSION_TYPE == "wayland" ]]
then
    exit
fi

USERNAME=fdlsifu
export XAUTHORITY=/home/$USERNAME/.Xauthority 
export DISPLAY=:0
connectedOutputs=$(xrandr | awk '$2 == "connected"{print $1}')
echo $USER >> /tmp/log
if [[ *"$connectedOutputs"* =~ "DP-1-1" ]] 
then 
    echo "desktop mode" >> /tmp/log
    
    pkill polybar
    xrandr --output DP-1-3 --mode 1920x1080 --pos 0x1080 --rate 74.97 --output DP-1-1 --mode 3840x2160 --pos 1920x0 --primary --rate 60 --output DP-1-2 --mode 1920x1080 --pos 5760x1080 --rate 74.97 --output eDP-1 --off

    bspwm_dynamic_desktop send eDP-1 DP-1-1
    bspc monitor eDP-1 -r
    bspc wm -O DP-1-3 DP-1-1 DP-1-2
    bspc wm -r
#    bspc wm -o
    
    cp ~/.xsettingsd120 ~/.xsettingsd
    pkill -HUP xsettingsd

    echo "Xft.dpi: 120" > ~/.Xresources
    echo "Xcursor.theme: Breeze_Snow" >> ~/.Xresources
    xrdb -merge ~/.Xresources

    echo $(date) >> /tmp/log
    echo "4K" >> /tmp/log
    echo "" >> /tmp/log

else
    echo "laptop mode" >> /tmp/log
    pkill polybar
    xrandr --output eDP-1 --primary --mode 1920x1200 --pos 7000x7000 --output DP-1-3 --off --output DP-1-1 --off --output DP-1-2 --off

    bspwm_dynamic_desktop send DP-1-1 eDP-1
    bspwm_dynamic_desktop send DP-1-2 eDP-1
    bspwm_dynamic_desktop send DP-1-3 eDP-1
    bspc monitor DP-1-1 -r
    bspc monitor DP-1-2 -r
    bspc monitor DP-1-3 -r
    bspc wm -r
#    bspc wm -o


    cp ~/.xsettingsd96 ~/.xsettingsd
    pkill -HUP xsettingsd

    echo "Xft.dpi: 96" > ~/.Xresources
    echo "Xcursor.theme: Breeze_Snow" >> ~/.Xresources
    xrdb -merge ~/.Xresources

    echo $(date) >> /tmp/log
    echo "2K" >> /tmp/log
    echo "" >> /tmp/log
fi

if [[ $1 == "no-bspwm-restart" ]]
then
    exit
else
    bspc wm -r
    bspwm_dynamic_desktop
fi
#i3-msg restart
