#!/bin/sh

revert() {
    xset dpms 0 0 0
}
trap revert HUP INT TERM
xset +dpms dpms 5 5 5

dunstctl set-paused true

#if [[ $(date +%H) -ge 20 || $(date +%H) -le 7 ]]; then kbd_lightup; else kbd_lightoff; fi


i3lock -c 222222 --nofork

dunstctl set-paused false

revert
