#!/bin/bash

# Airpods
DEVNAME="airpods"
DEVMAC="5C:52:30:E2:59:97"
DEVPULSE="bluez_output.5C_52_30_E2_59_97.a2dp-sink"

#Jaybird
#DEVNAME="jaybird"
#DEVMAC="C0:28:8D:A9:7E:8D"
#DEVPULSE="bluez_output.C0_28_8D_A9_7E_8D.a2dp-sink"

if [[ $(lsmod | grep hci_uart) == "" ]] 
then 
    zenity --password | sudo -S modprobe hci_uart
    sleep 5
fi

echo "power on" | bluetoothctl
# AirPods Pro
if [[ -z "$(pactl list | grep -i $DEVNAME)" ]]
then
 
    echo "connect $DEVMAC" | bluetoothctl

    # Waiting connection
    i=0
    while [[ $i -lt 10  && -z "$(pactl list | grep -i $DEVNAME)" ]]
        do 
            echo "waiting connection"
            sleep 1
            i=$((i+1))
        done
fi


if [[ -n "$(pactl list | grep -i $DEVNAME)" ]]
then
    echo "connected"
    pactl set-default-sink $DEVPULSE
    echo "set by default"
else
    echo "timeout"
fi
